

services:
  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - invoice-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 10s
      retries: 10
      interval: 10s

  # RabbitMQ Service
  rabbitmq-service:
    image: rabbitmq-service:latest
    container_name: rabbitmq-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=ec2
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - RABBITMQ_VHOST=/
      - RABBITMQ_AUTO_CONSUMER_ENABLED=true
      # Use H2 embedded instead of external for development  
      - ORACLE_DB_URL=jdbc:h2:mem:oracledb;DB_CLOSE_DELAY=-1;MODE=Oracle
      - ORACLE_DB_USERNAME=sa
      - ORACLE_DB_PASSWORD=
      - JPA_DDL_AUTO=create-drop
      - JPA_SHOW_SQL=false
      # JVM memory settings for low resource environment
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=100
      # Azure AD settings
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_JWK_SET_URI=${AZURE_JWK_SET_URI}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - invoice-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/rabbitmq/health"]
      timeout: 10s
      retries: 5
      interval: 30s

  # Invoice Service
  invoice-service:
    image: invoice-service:latest
    container_name: invoice-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=ec2
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - RABBITMQ_VHOST=/
      - RABBITMQ_ENABLED=true
      # JVM memory settings for low resource environment
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=100
      # Azure AD settings
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_JWK_SET_URI=${AZURE_JWK_SET_URI}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - invoice-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s

  # File Service
  file-service:
    image: file-service:latest
    container_name: file-service
    ports:
      - "8081:8081"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
    networks:
      - invoice-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s

volumes:
  rabbitmq_data:

networks:
  invoice-network:
    driver: bridge
