# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push file-service
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/file-service:latest \
            -f Dockerfile.file \
            .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/file-service:latest

      - name: Build & push invoice-service
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/invoice-service:latest \
            -f Dockerfile.invoice \
            .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/invoice-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1) Traemos las nuevas imágenes
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/file-service:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/invoice-service:latest

            # 2) Paramos y borramos versiones anteriores
            docker stop file-service invoice-service || true
            docker rm   file-service invoice-service || true

            # 3) Levantamos file-service, montando EFS exactamente
            #    donde tu app espera ver /mnt/efs/invoices
            docker run -d --name file-service \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e AWS_REGION=us-east-1 \
              -p 8081:8081 \
              -v /mnt/efs/invoices:/mnt/efs/invoices \
              ${{ secrets.DOCKERHUB_USERNAME }}/file-service:latest

            # 4) Levantamos invoice-service
            docker run -d --name invoice-service \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e AWS_REGION=us-east-1 \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/invoice-service:latest
